### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by kbond**
Symfony 6 is now released.

### CODE REVIEW

**Comment by insign** [comment]
Here we are.

**Comment by ejunker** [comment]
Laravel 9 will be released on February 8, 2022 and will require version 6 of the Symfony components. Looking forward to when this PR is merged.

**Comment by jdecode** [comment]
Being a product of "enlightn", I was expecting this be one of those packages which was going to be "Laravel-9-ready" from the moment (or rather before) Laravel 9 was launched (made default).

Would love to see this happening soon... :crossed_fingers:

**Comment by mglaman** [comment]
Can someone rerun the CI?

**Comment by paras-malhotra** [comment]
Thanks for the PR. This is now available in v1.10.0.

**Pull request merged**
