### PR TITLE
Fix requirements to allow supported versions of symfony and guzzle

### LINKED ISSUE #1: Allow all supported symfony versions
Currently, this package is not compatbile with Symfony <5.2 because it requires symfony/yaml:^5.2

I think it should be compatible with any supported Symfony version: currently ^3.4|^4.4|^5.2

What do you think?

### PR DESCRIPTION
**Pull request by ajgarlag**
This fixes #1

With guzzle <6.3 there is an error in tests, so guzzle ^6.3 is required.

### CODE REVIEW

**Comment by paras-malhotra** [comment]
Thanks for the pull request! Can you also add prefer-lowest and prefer-stable to the Github actions matrix to confirm all supported versions work?

Let me know if you aren't familiar with Github actions or don't have time to do this. I'll work on this PR in that case. Thanks again! 👍

**Comment by ajgarlag** [comment]
@paras-malhotra Done!

**Comment by paras-malhotra** [comment]
Thank you @ajgarlag. Can you change the console and finder dependencies to ^5.0 instead of ^5.2? syfmony/yaml 5.2 only requires symfony/console ^5.0.

I tried adding commits to this PR but I think you don't have the "Allow edits from maintainers" checkbox ticked. After this change, I'll merge. Thanks!

**Comment by ajgarlag** [comment]
@paras-malhotra Sorry, but I do not understand your review.

If you want to support Symfony 5.0 and 5.1 (currently unsupported by the symfony team), all three symfony packages (including symfony/yaml) should be modified to ^5.0

But for a security checking tool, I think that only supported versions or dependencies should be allowed.

**Comment by paras-malhotra** [comment]
@ajgarlag I understand. We can make all 3 as ^5.0. 

The idea is to allow downloading the tool even if there are unsupported / security issues. The tool itself will highlight the issues. Not being able to download the security checker would be a bigger concern! Therefore, we need to have a lax versioning policy and support all versions that work with the checker without any bugs.

**Comment by ajgarlag** [comment]
@paras-malhotra I've relaxed all Symfony packages to the lowest versions that make the tests pass.

**Comment by paras-malhotra** [comment]
Thank you @ajgarlag. Appreciate your PRs 👍  Will publish a release now.

**Pull request merged**
